# Generated by Django 3.1.1 on 2020-09-29 14:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.PositiveIntegerField(blank=True, choices=[(0, 'UK'), (1, 'SPAIN'), (2, 'TURKEY'), (3, 'GREECE'), (4, 'THAILAND'), (5, 'COLUMBIA'), (6, 'DOMINICAN_REPUBLIC'), (7, 'MEXICO'), (8, 'COSTA_RICA'), (9, 'BELGIUM')], default=0)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('Location', models.CharField(max_length=50)),
                ('summary', models.TextField(default='Testing')),
                ('virtual_consultation', models.BooleanField(default=False)),
                ('languages', models.PositiveIntegerField(blank=True, choices=[(0, 'English'), (1, 'Spanish'), (2, 'French'), (3, 'German'), (4, 'Chinese'), (5, 'Turkish'), (6, 'Russian'), (7, 'Arabic'), (8, 'Punjabi'), (9, 'Japanese')], default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('price_quote_available', models.BooleanField(default=False)),
                ('country', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.country')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=30)),
                ('nos', models.DecimalField(decimal_places=0, max_digits=2)),
                ('price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('status', models.CharField(choices=[('B', 'Booked'), ('C', 'Cancelled')], default='B', max_length=255)),
                ('doctor_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.doctor')),
                ('user_id', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='app.user')),
            ],
        ),
    ]
