# Generated by Django 3.1.1 on 2020-09-29 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='email',
        ),
        migrations.RemoveField(
            model_name='book',
            name='name',
        ),
        migrations.AddField(
            model_name='doctor',
            name='years_experience',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
