# Generated by Django 3.1.1 on 2020-09-29 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200929_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='main_img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
