# Generated by Django 3.1.1 on 2020-09-29 15:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_doctor_main_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='created_at',
            field=models.TimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
