# Generated by Django 3.1.1 on 2020-09-29 16:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20200929_1603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.country'),
        ),
    ]
