# Generated by Django 3.1.1 on 2020-10-02 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_auto_20200929_1605'),
    ]

    operations = [
        migrations.CreateModel(
            name='Procedure',
            fields=[
                ('procedure_id', models.AutoField(primary_key=True, serialize=False)),
                ('procedure_name', models.CharField(choices=[('BBL', 'BBL'), ('BA', 'BREAST AUGMENTATION'), ('RHP', 'RHINOPLASTY')], max_length=30)),
                ('Procedure_description', models.TextField(default='Description')),
            ],
        ),
    ]
