# Generated by Django 3.1.1 on 2020-10-02 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_procedure'),
    ]

    operations = [
        migrations.AddField(
            model_name='procedure',
            name='doctors',
            field=models.ManyToManyField(to='app.Doctor'),
        ),
    ]
