# Generated by Django 3.1.1 on 2020-10-02 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_procedure_doctors'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='procedures',
            field=models.ManyToManyField(to='app.Procedure'),
        ),
    ]
