# Generated by Django 3.1.1 on 2020-10-03 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_doctor_procedures'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctor',
            old_name='Location',
            new_name='location',
        ),
    ]
