# Generated by Django 3.1.1 on 2020-10-03 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20201003_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(choices=[(1, 'BBL'), (2, 'BREAST AUGMENTATION'), (3, 'RHINOPLASTY')], max_length=30),
        ),
    ]
