# Generated by Django 3.1.1 on 2020-10-04 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_auto_20201003_1332'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='Procedure_description',
            new_name='procedure_description',
        ),
        migrations.RemoveField(
            model_name='procedure',
            name='doctors',
        ),
    ]
