# Generated by Django 3.1.1 on 2020-10-04 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0012_auto_20201004_1258'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='user_id',
        ),
        migrations.AddField(
            model_name='booking',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='languages',
            field=models.CharField(default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='procedure',
            name='procedure_name',
            field=models.CharField(max_length=30),
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
