# Generated by Django 3.1.1 on 2020-10-13 20:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20201004_1414'),
    ]

    operations = [
        migrations.RenameField(
            model_name='procedure',
            old_name='procedure_id',
            new_name='id',
        ),
    ]
