# Generated by Django 3.1.1 on 2020-10-17 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_auto_20201013_2048'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='languages',
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.ManyToManyField(to='app.Language'),
        ),
    ]
