# Generated by Django 3.1.1 on 2020-10-17 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_auto_20201017_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='languages',
        ),
        migrations.DeleteModel(
            name='Language',
        ),
    ]
