# Generated by Django 3.1.1 on 2020-09-28 16:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('address', models.TextField(default='Testing')),
                ('virtual_consultation', models.BooleanField(default=False)),
                ('languages', models.PositiveIntegerField(blank=True, choices=[(0, 'English'), (1, 'Spanish'), (2, 'French'), (3, 'German'), (4, 'Chinese')], default=0)),
                ('rating', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)])),
                ('price_quote_available', models.BooleanField(default=False)),
                ('county', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='consultation.country')),
            ],
        ),
    ]
