# Generated by Django 3.1.1 on 2020-09-27 14:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0002_doctor_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='languages',
            field=models.IntegerField(blank=True, choices=[(0, 'English'), (1, 'Spanish'), (2, 'French'), (3, 'German'), (4, 'Chinese')], default='Testing'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='price_quote_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='rating',
            field=models.PositiveIntegerField(default='0', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10)]),
        ),
        migrations.AddField(
            model_name='doctor',
            name='virtual_consultation',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='doctor',
            name='county',
            field=models.ForeignKey(default='Testing', on_delete=django.db.models.deletion.CASCADE, to='consultation.country'),
        ),
    ]
