# Generated by Django 3.1.1 on 2020-09-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultation', '0003_auto_20200927_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='languages',
            field=models.IntegerField(blank=True, choices=[(0, 'English'), (1, 'Spanish'), (2, 'French'), (3, 'German'), (4, 'Chinese')], default='0'),
        ),
    ]
